channels:
  - conda-forge
  - nodefaults
dependencies:
  - jupyterlab
  - python =3.11
  - numpy >1.20,<2
  - matplotlib
  - pyiron_workflow =0.12.0
  - pyironflow =0.0.9
  - pip:
    - git+https://github.com/pmrv/python-ace.git
    - tensorpotential ==0.4.5
